# -*- coding: utf-8 -*-
"""
Created on Wed May 15 09:44:48 2019

@author: msjor
"""
############################################# Imports #################################################
import numpy as np

############################################# Functions ###############################################

def panel_area(t_o, t_e, pr_day, pr_eclipse, theta = 0):
     """t_o = orbital time [sec]
        t_e = eclipse time [sec]
        pr_day = power required during the day [W]
        pr_eclipse = power required during eclipse [W]
        theta = incidence angle [rad]"""
    
    #Mission parameters
    t_d = t_o - t_e #day time [s]
    T = 10 #mission lifetime [years]
    sr = 1358 #solar radiation [W/m^2]
   
    #efficiencies
    eff = 0.28 #solar panel efficiency
    eff_c = 0.9 #path efficiency panels to equipments
    eff_dc = 0.85 #path efficiency panels through batteries to equipment
    
    #solar panel characterisitcs
    wkg = 100 #[W/kg]
    d = 0.9725 #yearly degradation 
    
    #compute required powerzzzz during day and eclipse
    pr_day = pr_day/eff_c #power required during the day EOL [W]
    pr_eclipse = pr_eclipse/eff_dc #power required during eclipse EOL [W]
    
    #EQUATIONS
    pbol = ((pr_day*t_d+pr_eclipse*t_e)/(t_d)/(d**T))/np.cos(theta) #bol power accounting for degradation, eclipse time, incidence angle
    
    psol = pbol/eff #power that needs to be generated by solar panels accounting for their efficiency
    
    #compute area and mass of panels
    A = psol/sr #area
    m = pbol/wkg #mass
        
    return A, m

def comms_mass(power_transmitter, area_antenna, dens_antenna):
    """power_transmitter = power required by the transmitter on the spacecraft [W]
       Area of the antenna [m^2]
       dens_antenna = density of the antenna [kg/m^2], typical values 5-8""" 
   #transmitter characteristics    
   specific_power = 2.9 #W/kg
   dens_trans = 0.75*10**-3 #kg/m3
   mass_trans = power_transmitter/specific_power  #kg
   vol_trans = mass_trans/dens_trans  #m3
   
   #mass of the amplifier 
   mass_amp = 0.07*power_transmitter+0.634 #kg
   
   #Antenna characterisics
   mass_antenna = dens_antenna * area_antenna #kg, antenna on board of spacecraft
   
   #Combine to find mass total communications system
   total_mass = (mass_antenna + mass_amp + mass_trans)*1.3

   return total_mass, vol_trans

